/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_armeeting_OpenCvUtils */

#ifndef _Included_com_example_armeeting_OpenCvUtils
#define _Included_com_example_armeeting_OpenCvUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_armeeting_OpenCvUtils
 * Method:    detectFinger
 * Signature: (IILjava/nio/ByteBuffer;Landroid/view/Surface;)Ljava/lang/String;
 */
JNIEXPORT jint JNICALL Java_com_example_armeeting_OpenCvUtils_detectFinger
  (JNIEnv *, jclass, jint, jint, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif