/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_armeeting_JNIUtils */

#ifndef _Included_com_example_armeeting_JNIUtils
#define _Included_com_example_armeeting_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_armeeting_JNIUtils
 * Method:    detectFinger
 * Signature: (IIJLandroid/view/Surface;)I
 */
JNIEXPORT jint JNICALL Java_com_example_armeeting_JNIUtils_detectFinger
  (JNIEnv *, jclass, jint, jint, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif